### ISSUE TITLE
Add an input box that the user can interact with to submit locations and a button below that will generate our optimized route

### ISSUE THREAD

**Issue by KLanger98** [KLanger98/AsTheCrowDrives#3]
User Story:
As a traveller I will load the route optimization tool and I will be presented with an initial input box that will save my added locations. When they are saved they will be added to the word document in the form of a row of divs which I can then interact with to remove if needed. There will also be a large button below this container I can click to generate my optimized route based on the locations provided earlier. 

Acceptance criteria:
When I load the webpage 
Then I am presented with two containers, one containing the search form and one containing the generate route button. 
When I search a location
Then the location is pushed to a row below the search box containing all searched locations 
When I press the generate route button
Then the previously saved locations will be cleared from display

![Screenshot 2024-01-23 at 9 10 42 pm](https://github.com/KLanger98/AsTheCrowDrives/assets/85721194/3a1024ec-6f0b-4be5-9476-2add7d678852)

**Comment by BadrulBorhanudin** [comment]
Done with later optimisations will follow as we go.
